print("Hello, World!")
print("This is a sample Python script.")
print("It demonstrates basic print functionality.")
print("Feel free to modify and expand it as needed.")
print("Goodbye, World!")
print("End of the script.")
print("This line has been added to the script.")
print("Another line for demonstration purposes.")
print("Final line of the script.")
print("Script execution complete.")
print("Thank you for using this script."